# Generated by Django 5.0.1 on 2024-01-31 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Основная категория",
                "verbose_name_plural": "Основные категории",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название")),
                ("slug", models.SlugField(blank=True, null=True, unique=True, verbose_name="Slug")),
                (
                    "main_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_categories",
                        to="shop.maincategory",
                        verbose_name="Основная категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True, verbose_name="Название")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="products/%Y/%m/%d", verbose_name="Фотография"),
                ),
                ("count", models.PositiveIntegerField(default=0, verbose_name="Количество товара")),
                (
                    "condition",
                    models.CharField(
                        choices=[("NEW", "Новый"), ("USED", "Б/У")],
                        max_length=100,
                        unique=True,
                        verbose_name="Состояние",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=20, verbose_name="Цена")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                ("slug", models.SlugField(blank=True, null=True, unique=True, verbose_name="Slug")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="shop.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
